# Generated by Django 4.0.4 on 2022-05-12 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0002_category'),
        ('rareapi', '0002_post'),
    ]

    operations = [
    ]
