# Generated by Django 4.0.4 on 2022-05-12 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0002_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='user',
        ),
    ]
