# Generated by Django 4.0.4 on 2022-05-12 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0003_merge_0002_category_0002_post'),
        ('rareapi', '0003_rename_author_post_user'),
    ]

    operations = [
    ]
