# Generated by Django 4.0.4 on 2022-05-12 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0004_post_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(related_name='posttag', to='rareapi.tag'),
        ),
    ]
