# Generated by Django 4.0.4 on 2022-05-12 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0004_merge_0003_comment_0003_merge_0002_category_0002_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post_id',
            new_name='post',
        ),
    ]
