# Generated by Django 4.0.4 on 2022-05-12 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0004_merge_20220512_1439'),
        ('rareapi', '0005_rename_post_id_comment_post'),
    ]

    operations = [
    ]
