# Generated by Django 4.0.4 on 2022-05-12 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0007_merge_20220512_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='subject',
            field=models.CharField(default='games', max_length=30),
            preserve_default=False,
        ),
    ]
