# Generated by Django 4.0.4 on 2022-05-12 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0007_rename_user_post_author'),
        ('rareapi', '0008_comment_subject'),
    ]

    operations = [
    ]
